### ISSUE TITLE
disconnect 

### ISSUE THREAD

**Issue by ludovicbernard** [wpietrzakpl/GlpiTools#11]
Hi, 
can we disconnect a device (monitor , printer ) from the computer view ?

**Comment by wpietrzakpl** [comment]
Hi,

Its not so easy... First you have to get from database name of the table which store this data 
Later you can add it to module and try to remove items from there using Remove-GlpiToolsItems

**Comment by wpietrzakpl** [comment]
no respond, seems sorted out
