### ISSUE TITLE
bug Add-GlpiToolsTicketFollowup

### ISSUE THREAD

**Issue by ludovicbernard** [wpietrzakpl/GlpiTools#14]
I have an error message when executing the function, "ERROR_GLPI_ADD", "you do not have the rights required to perform this action.
when I run the Add-GlpiToolsTicketTask function, I have no error message and it is executed
can you tell me if the order conforms
Add-GlpiToolsTicketFollowup -ticket_id 55555 -content "test"
thank you

**Comment by ludovicbernard** [comment]
ticket de formcreator

**Comment by wpietrzakpl** [comment]
Hi Error about rights is a problem with rights of the account that you are using with API 
Please check rights first

**Comment by wpietrzakpl** [comment]
no info
