### ISSUE TITLE
It's just that I never know how to import the information in the sub-project, such as ip address, mac address and so on

### ISSUE THREAD

**Issue by iamtornado** [wpietrzakpl/GlpiTools#17]
hello：
I now know how to import basic project information through glpitools, such as computer name, serial number, etc. It's just that I never know how to import the information in the sub-project, such as ip address, mac address and so on. The following figure shows the network information of the server collected by the fusioninventory agent. If I use glpitools, how should I import this information?
![image](https://user-images.githubusercontent.com/84172976/128144865-af3c1aa3-790c-46f3-b0b4-b07a0f9d29bc.png)
thanks

**Comment by wpietrzakpl** [comment]
Hello, 
Yes, there is a way to do this
Follow the steps to add new parameter called "Item_DeviceNetworkCard" to parameters.json (Here is how to do this - https://www.wpietrzak.pl/glpi/ThingsToKnowGlpiTools/ section parameters.json)

and then: 
Get-GlpiToolsItems -ItemType Item_DeviceNetworkCard - to find required network which is associated with computer

and you can update with: 

$example = @{mac = "20:6a:8a:a9:75:81"}
Update-GlpiToolsItems -UpdateTo Item_DeviceNetworkCard -ItemId <put here id from previous command> -ItemsHashtableWithoutId $example

you can easly find me on Discord, feel free to catch me there !

**Comment by iamtornado** [comment]
Hi，
I found that the parameter.json file already contains the networkcard component, but I did not find the associated computer with this command, it is actually associated with a computer, as shown below：
![image](https://user-images.githubusercontent.com/84172976/128278600-482619a9-c087-4f06-89e0-f7df5f285d5d.png)
![image](https://user-images.githubusercontent.com/84172976/128278635-b3737010-82e1-4534-8b32-0c311e613ec8.png)
In addition, the most important thing is that I actually want to achieve this goal:
I used the powershell module PowerCLI developed by VMware to obtain the information of virtual machines in VMware vcenter. I want to import the information of these virtual machines into glpi. The following figure illustrates how I obtain the information of virtual machines in VMware vcenter.
![image](https://user-images.githubusercontent.com/84172976/128279537-bcf85b7d-6db6-491f-86e7-157fe30af25b.png)
Since there is no corresponding relationship between virtual machine and network information in glpi, I really don’t understand how to associate Computer with network information. If this is not clear, then I cannot import the obtained virtual machine information into glpi.

**Comment by wpietrzakpl** [comment]
Maybe it wasn't clear but as I wrote you need **"Item_DeviceNetworkCard"** to get the network cards 
I am pretty sure that you can do it !

**Comment by wpietrzakpl** [comment]
you can add this endpoint to the parameters.json "ipaddress" 
this one will give you all IP addresses, and with this information you can filter the list with items_id which is id of computer 
and then you can update this as I showed you

**Comment by wpietrzakpl** [comment]
do you have more questions ? if not, I would close the issue

**Comment by iamtornado** [comment]
hi，
According to what you said, I added "ipadress" to the parameters.json file. You can indeed get all the existing ip address information in glpi through the Get-GlpiToolsItems -ItemType ipaddress command. But the current situation is that I want to import the ip information into glpi, but it is not successful, as shown in the following figure:
![image](https://user-images.githubusercontent.com/84172976/128831253-343b22f3-8446-4a52-bb75-594c01ce234a.png)

**Comment by wpietrzakpl** [comment]
look how I did it 
![image](https://user-images.githubusercontent.com/11921969/128930709-c809f651-3673-4503-bd57-24bee15fe534.png)
the most important here is "items_id" parameter - this is ID of Network Name which is Associated with Computer 

Without this it would not work

**Comment by iamtornado** [comment]
I think I understand what you mean, according to what you said, I successfully added ip
`$example = @{name = "10.30.1.3";items_id = 4;itemtype = "NetworkName"}
$networkname =@{name = "dvportgroup-334"}
$itemtype = @{itemtype = "networkport"}
Add-GlpiToolsItems -AddTo networkname -HashtableToAdd $networkname
Update-GlpiToolsItems -UpdateTo networkname -ItemId 4 -ItemsHashtableWithoutId $itemtype
Add-GlpiToolsItems -AddTo ipaddress -HashtableToAdd $example`
![image](https://user-images.githubusercontent.com/84172976/128955951-403080f4-9ef0-464b-9c86-94f594ee8a00.png)

**Comment by iamtornado** [comment]
thank you very much! You let me know more about the data structure of glpi.
I think that if you want to make full use of glpi restapi, you still have to understand the structure of glpi's database and understand the relationship between the tables. I still have to learn the knowledge of the database
