### ISSUE TITLE
the additional fields

### ISSUE THREAD

**Issue by ludovicbernard** [wpietrzakpl/GlpiTools#9]
Hi,
on our glpi, we use the additional fields for example,
the name of the field mac, on the view of glpi, we have, plugins - MAC - MAC, how to retrieve the information of this field
thank you for your help

**Comment by wpietrzakpl** [comment]
Hi,

If you added Field MAC to view of the user which you use to use API, you can get it by:
$Asset = Search-GlpiToolsItems -SearchFor <type> -SearchType contains -SearchValue <name>
$Asset."MAC - MAC"

**Comment by ludovicbernard** [comment]
ok I have the info of the field "MAC - MAC" 
merci.

**Comment by wpietrzakpl** [comment]
No problem :)
